#cloud-config
package_update: true
package_upgrade: true
packages:
  - git

groups:
  - ars

users:
  - default
  - name: ars
    primary_group: ars
    shell: /bin/bash
    homedir: /home/ars

runcmd:
  - echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> /etc/environment
  - cd /home/ars
  - git clone --branch release/v1.0.0 --depth 1 https://${GH_PAT}@github.com/neuvo-ai/ars.git .
  - echo "REACT_APP_GEMINI_API_KEY=${REACT_APP_GEMINI_API_KEY}" > .env
  - chown -R ars:ars /home/ars
