name: Deploy Release v1 to AWS

on:
  workflow_dispatch:
    inputs:
      region:
        description: "Choose AWS region"
        required: true
        default: eu-north-1
        type: choice
        options:
          - eu-north-1
          - eu-west-1
      instance_type:
        description: 'EC2 Instance Type (Minimum Requirement: 2xvCPU 4G RAM)'
        required: true
        default: 't3.medium'
      ami_id:
        description: 'AMI ID (ami-xxxxxxxxxxxx)'
        required: true
      security_group_id:
        description: 'Security Group ID (sg-xxxxxxxxxxxxxx)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release v1.0.0
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare cloud-init file with GitHub token
        run: |
          export GH_PAT=${{ secrets.GH_PAT }}
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          export REACT_APP_GEMINI_API_KEY=${{ secrets.REACT_APP_GEMINI_API_KEY }}
          envsubst < devops/cloud-init/release-v1.yml > user-data.yml

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Launch EC2 instance
        run: |
          echo "Launching EC2 instance in region ${{ github.event.inputs.region }}..."

          INSTANCE_ID=$(aws ec2 run-instances \
            --region "${{ github.event.inputs.region }}"
            --image-id "${{ github.event.inputs.ami_id }}" \
            --count 1 \
            --key-name ars \
            --instance-type "${{ github.event.inputs.instance_type }}" \
            --user-data file://user-data.yml \
            --security-group-ids "${{ github.event.inputs.security_group_id }}" \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=ars}]' \
            --query 'Instances[0].InstanceId' \
            --output text)

          echo "Instance launched: $INSTANCE_ID"

          aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"

          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids "$INSTANCE_ID" \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)

          echo "Public IP: $PUBLIC_IP"

          # Information showing on the summary
          {
            echo "## EC2 Instance Launched"
            echo ""
            echo "- **Instance ID:** \`$INSTANCE_ID\`"
            echo "- **Region:** \`${{ github.event.inputs.region }}\`"
            echo "- **Type:** \`${{ github.event.inputs.instance_type }}\`"
            echo "- **Public IP:** \`$PUBLIC_IP\`"
          } >> "$GITHUB_STEP_SUMMARY"